service: java-lambda-subject-rate-link

provider:
  name: aws
  runtime: java8
  profile: ${env:PROFILE, 'uvsy-sls-dev'}
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION, 'sa-east-1'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:UpdateItem"
        - "dynamodb:ListStreams"
        - "dynamodb:GetRecords"
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}

package:
  artifact: build/distributions/${self:service}-1.0.zip

functions:
  subjectRateLink:
    name: ${self:provider.stage}-${self:service}
    handler: com.universy.subject.rate.StudentSubjectRateDynamoHandler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::ImportValue: "student-subject-rate:${self:provider.stage}:TableStreamArn"
