Resources:
  get:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/run
      Handler: com.universy.institution.subject.rate.InstitutionSubjectRateGetHandler
      Runtime: java8
      MemorySize: 512
      Timeout: 300
      Environment:
        Variables:
          AWS_REGION: sa-east-1
          STAGE: dev